name: Build release APK
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_MAXSIZE: "10G"
      CCACHE_HARDLINK: "true"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # 关键修改：关闭递归拉取子模块，避开那个私有仓库
          submodules: false
          fetch-depth: 1

      - name: Write API Keys
        uses: DamianReeves/write-file-action@master
        with:
          path: ./API_KEYS
          contents: |
            APP_ID = 37274250
            APP_HASH = "5205cbdae6cecc6ce1bd494b5685fe16"
            MAPS_V2_API = ${{ secrets.MAPS_KEY }}
            
            SIGNING_KEY_PASSWORD = ${{ secrets.CERT_KEY }}
            SIGNING_KEY_ALIAS = ${{ secrets.CERT_KEY }}
            SIGNING_KEY_STORE_PASSWORD = ${{ secrets.CERT_KEY }}
          write-mode: overwrite

      - name: Update packages
        run: sudo apt-get update

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v3

      - name: Prepare Environment
        run: |
          sudo apt-get remove -y '^llvm-.*' 'php.*' '^mongodb-.*' '^mysql-.*' azure-cli firefox mono-devel libgl1-mesa-dri
          sudo apt-get autoremove -y
          sudo apt-get clean
          sudo rm -rf /usr/share/dotnet/ /usr/local/graalvm/ /usr/local/.ghcup/ /usr/local/share/powershell /usr/local/share/chromium /usr/local/lib/node_modules
          sudo apt-get install bison gcc make curl ninja-build ccache -y

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleAfatRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Release-APK
          path: TMessagesProj/build/outputs/apk/afat/release/*.apk
